
import { WorkType } from './types';

export const DICTIONARY = {
  ar: {
    APP_TITLE: 'Movesongs',
    APP_DESCRIPTION: 'تحليلات سينمائية، أدبية وموسيقية معمّقة',
    WORK_NAME_LABEL: 'اسم العمل (فيلم، مسلسل، كتاب، أغنية)',
    WORK_NAME_PLACEHOLDER: 'مثال: فيلم The Matrix، رواية 1984، أو أغنية "عطني الناي"',
    GENERATE_ANALYSIS: 'توليد التحليل',
    GENERATING_ANALYSIS: 'جاري توليد التحليل...',
    ANALYSIS_RESULT_TITLE: 'نتائج التحليل',
    CLEAR_ANALYSIS: 'تحليل جديد',
    ANALYSIS_TAB: 'تحليل',
    HISTORY_TAB: 'الأرشيف',
    EMPTY_HISTORY: 'لا يوجد تحليلات محفوظة في الأرشيف بعد.',
    SHARE_ANALYSIS: 'مشاركة التحليل',
    COPIED_SUCCESS: 'تم النسخ!',
    COPY_TEXT: 'نسخ النص',
    EXPORT_TO_PDF: 'تصدير كـ PDF',
    SAVE_TO_DRIVE: 'حفظ في Google Drive',
    FEATURE_COMING_SOON: 'الميزة قادمة قريبًا!',
    VIEW_ANALYSIS: 'عرض التحليل',
    DELETE_ANALYSIS: 'حذف التحليل',
    SPOILERS: 'إخفاء حرق الأحداث',
    QUOTES: 'إدراج اقتباسات',
    WORD_COUNT_LABEL: 'طول المقال التقريبي',
    WORDS: 'كلمة',
  },
  en: {
    APP_TITLE: 'Movesongs',
    APP_DESCRIPTION: 'In-depth cinematic, literary, and musical analysis',
    WORK_NAME_LABEL: 'Work Name (Film, Series, Book, Song)',
    WORK_NAME_PLACEHOLDER: 'e.g., The Matrix, 1984, or "Bohemian Rhapsody"',
    GENERATE_ANALYSIS: 'Generate Analysis',
    GENERATING_ANALYSIS: 'Generating Analysis...',
    ANALYSIS_RESULT_TITLE: 'Analysis Results',
    CLEAR_ANALYSIS: 'New Analysis',
    ANALYSIS_TAB: 'Analysis',
    HISTORY_TAB: 'History',
    EMPTY_HISTORY: 'No analysis history yet.',
    SHARE_ANALYSIS: 'Share Analysis',
    COPIED_SUCCESS: 'Copied!',
    COPY_TEXT: 'Copy Text',
    EXPORT_TO_PDF: 'Export as PDF',
    SAVE_TO_DRIVE: 'Save to Google Drive',
    FEATURE_COMING_SOON: 'Feature coming soon!',
    VIEW_ANALYSIS: 'View Analysis',
    DELETE_ANALYSIS: 'Delete Analysis',
    SPOILERS: 'Hide Spoilers',
    QUOTES: 'Include Quotes',
    WORD_COUNT_LABEL: 'Approximate Article Length',
    WORDS: 'words',
  }
};

export const UI_LABELS = DICTIONARY.ar;

// Dynamic Analysis Angles based on Work Type
export const WORK_TYPE_ANGLES: Record<WorkType, string[]> = {
  [WorkType.Auto]: [
    'فلسفي',
    'نفسي',
    'اجتماعي',
    'فني/جمالي',
    'سيميائي (رموز)',
    'تاريخي',
  ],
  [WorkType.Film]: [
    'السيناريو والحوار',
    'التصوير والإضاءة',
    'الإخراج والرؤية البصرية',
    'التمثيل والأداء',
    'المونتاج والإيقاع',
    'الموسيقى وتصميم الصوت',
    'الرموز والدلالات',
    'الأبعاد الفلسفية',
  ],
  [WorkType.Series]: [
    'تطور الشخصيات (Arc)',
    'البناء الدرامي عبر المواسم',
    'إيقاع الأحداث (Pacing)',
    'الحوار واللغة',
    'بناء العالم (World Building)',
    'الحبكات الفرعية',
    'الأبعاد الاجتماعية',
    'النهايات والقفلات',
  ],
  [WorkType.Song]: [
    'الكلمات والصور الشعرية',
    'اللحن والمقامات',
    'التوزيع الموسيقي والآلات',
    'الأداء الصوتي والاحساس',
    'الإيقاع والوزن',
    'الجو العام (Mood)',
    'رسالة الأغنية',
    'الفيديو كليب (إن وجد)',
  ],
  [WorkType.Book]: [
    'الحبكة والبناء القصصي (للروايات)',
    'عمق الشخصيات (للروايات)',
    'المنهجية والأفكار العملية (للكتب غير الروائية)',
    'قوة الحجج والأدلة (للكتب الفكرية)',
    'قابلية التطبيق والتأثير (للكتب العملية)',
    'الأسلوب السردي واللغة',
    'الرمزية والثيمات الفكرية',
    'السياق التاريخي والاجتماعي',
  ],
};
