export const UI_LABELS = {
  APP_TITLE: 'Movesongs',
  APP_DESCRIPTION: 'تحليلات سينمائية وموسيقية معمّقة',
  WORK_NAME_LABEL: 'اسم الفيلم أو الأغنية',
  WORK_NAME_PLACEHOLDER: 'مثال: فيلم The Matrix أو أغنية "عطني الناي"',
  GENERATE_ANALYSIS: 'توليد التحليل',
  GENERATING_ANALYSIS: 'جاري توليد التحليل...',
  ANALYSIS_RESULT_TITLE: 'نتائج التحليل',
  CLEAR_ANALYSIS: 'تحليل جديد',
  ANALYSIS_TAB: 'تحليل',
  HISTORY_TAB: 'الأرشيف',
  EMPTY_HISTORY: 'لا يوجد تحليلات محفوظة في الأرشيف بعد.',
  SHARE_ANALYSIS: 'مشاركة التحليل',
  COPIED_SUCCESS: 'تم النسخ!',
  COPY_TEXT: 'نسخ النص',
  EXPORT_TO_PDF: 'تصدير كـ PDF',
  SAVE_TO_DRIVE: 'حفظ في Google Drive',
  FEATURE_COMING_SOON: 'الميزة قادمة قريبًا!',
  VIEW_ANALYSIS: 'عرض التحليل',
  DELETE_ANALYSIS: 'حذف التحليل',
  SPOILERS: 'إخفاء حرق الأحداث',
  QUOTES: 'إدراج اقتباسات',
};
